name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  # See https://github.com/docker/build-push-action/blob/master/docs/advanced/share-image-jobs.md
  # and https://stackoverflow.com/a/69324657/2826337
  # and https://depot.dev/blog/docker-layer-caching-in-github-actions
  # and https://docs.docker.com/engine/reference/commandline/buildx_build/
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    -
      name: Generate docker image name:tag
      # Should this incorporate the ${{ github.ref_name }} as well as the date?
      run: echo "img_name_tag=build_stack_exposures:$(date +%s)" >> $GITHUB_ENV
    -
      name: Checkout
      uses: actions/checkout@v3
    - 
      name: Checkout submodules
      run: |
        git submodule init
        git submodule update
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Build Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        tags: ${{ env.img_name_tag }}
        cache-to: type=gha,mode=max
        cache-from: type=gha
        outputs: type=docker,dest=/tmp/build_stack_exposures.tar
    -
      name: Load Docker image
      run: |
        docker load --input /tmp/build_stack_exposures.tar
    -
      name: Build stack_exposures
      run: |
        mkdir -p build_artifacts
        docker run --rm -v${PWD}:/source --user root ${{ env.img_name_tag }}
    -
      name: Run coverage tests
      run: |
        docker run --rm -v${PWD}:/source --user root ${{ env.img_name_tag }} "/source/scripts/docker/in_container/test.sh"
    -
      name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: build_artifacts