name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Checkout submodules
      run: |
        git submodule init
        git submodule update
    - name: Generate docker name:tag
      run: echo "name_tag=build_stack_exposures:$(date +%s)" >> $GITHUB_ENV
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ env.name_tag }}
    - name: Build stack_exposures using Docker
      run: |
        mkdir -p build_artifacts
        docker run --rm -v${PWD}:/source --user root ${{ env.name_tag }}
    - name: Run coverage tests
      run: |
        docker run --rm -v${PWD}:/source --user root ${{ env.name_tag }} "/source/docker_scripts/in_container/test.sh"
    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: build_artifacts